export const scentFamiliesData = [
        {
            "scentFamilyId": 2,
            "name":"citrus", 
            "note": "top",
            "scents":[
                {
                    "scentId": 2001,
                    "name":"Bergamot",
                    "latinName": "Citrus bergamia",
                    "color": "lch(75% 44 120)",
                    "colorFallback": "hsl(84 54% 53%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2002,
                    "name":"Bitter Orange or Bigarade",
                    "latinName": "Citrus × aurantium",
                    "color": "lch(81% 40 75)",
                    "colorFallback": "hsl(37 94% 67%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2003,
                    "name":"Blood Orange",
                    "latinName": "Citrus × sinensis",
                    "color": "lch(40% 56 41)",
                    "colorFallback": "hsl(3 100% 37%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2004,
                    "name":"Calamansi",
                    "latinName": "Citrus × microcarpa",
                    "color": "lch(51% 37 113)",
                    "colorFallback": "hsl(75 82% 28%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2005,
                    "name":"Chenpi",
                    "latinName": "Citri Reticulatae Pericarpium",
                    "color": "lch(68% 33 69)",
                    "colorFallback": "hsl(33 60% 57%)",
                    "isBasic": false,
                    "image": null,
                    "description": "Chenpi, chen pi, or chimpi is sun-dried mandarin orange peel used as a traditional seasoning in Chinese cooking and traditional medicine.",
                    "referenceLink": null
                },
                {
                    "scentId": 2006,
                    "name":"Chinotto",
                    "latinName": "Citrus myrtifolia",
                    "color": "lch(72% 50 80)",
                    "colorFallback": "hsl(45 100% 43%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2007,
                    "name":"Citron",
                    "latinName": "Citrus medica",
                    "color": "lch(90% 76 98)",
                    "colorFallback": "hsl(54 94% 63%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2008,
                    "name":"Clementine or Algerian Tangerine",
                    "latinName": "Citrus × clementina",
                    "color": "lch(75% 55 71)",
                    "colorFallback": "hsl(39 98% 50%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2009,
                    "name":"Finger Lime or Caviar lemon",
                    "latinName": "Citrus australasica",
                    "color": "lch(86% 12 133)",
                    "colorFallback": "hsl(103 32% 81%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2010,
                    "name":"Grapefruit",
                    "latinName": "Citrus × paradisi",
                    "color": "lch(47% 47 38)",
                    "colorFallback": "hsl(7 66% 47%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2011,
                    "name":"Hassaku",
                    "latinName": "Citrus × hassaku",
                    "color": "lch(86% 57 86)",
                    "colorFallback": "hsl(49 100% 50%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2012,
                    "name":"Hatkora Lemon or Shatkora",
                    "latinName": "Citrus macroptera",
                    "color": "lch(100% 29 129)",
                    "colorFallback": "hsl(98 31% 48%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2013,
                    "name":"Kaffir Lime",
                    "latinName": "Citrus hystrix",
                    "color": "lch(68% 33 122)",
                    "colorFallback": "hsl(87 38% 51%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2014,
                    "name":"Kumquat",
                    "latinName": "Citrus japonica",
                    "color": "lch(83% 48 82)",
                    "colorFallback": "hsl(43 97% 62%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2015,
                    "name":"Lemon",
                    "latinName": "Citrus limon",
                    "color": "lch(92% 41 93)",
                    "colorFallback": "hsl(51 100% 71%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2016,
                    "name":"Lemon Verbena, Lemon Beebrush",
                    "latinName": "Aloysia citrodora",
                    "color": "lch(79% 38 118)",
                    "colorFallback": "hsl(81 55% 60%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2017,
                    "name":"Lemon Zest",
                    "latinName": "Citrus limon",
                    "color": "lch(91% 41 93)",
                    "colorFallback": "hsl(51 100% 70%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2018,
                    "name":"Lemongrass",
                    "latinName": "Cymbopogon",
                    "color": "lch(76% 33 112)",
                    "colorFallback": "hsl(74 45% 58%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2019,
                    "name":"Lime",
                    "latinName": "Citrus aurantifolia",
                    "color": "lch(54% 36 123)",
                    "colorFallback": "hsl(89 53% 36%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2020,
                    "name":"Limetta, Sweet Lime",
                    "latinName": "Citrus Limetta",
                    "color": "lch(69% 46 113)",
                    "colorFallback": "hsl(75 69% 42%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2021,
                    "name":"Mandarin",
                    "latinName": "Citrus Reticulata",
                    "color": "lch(66% 44 58)",
                    "colorFallback": "hsl(26 79% 57%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2022,
                    "name":"Neroli, Orange Blossom",
                    "latinName": "Citrus aurantium ssp. amara",
                    "color": "lch(89% 1 38)",
                    "colorFallback": "hsl(15 8% 88%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2023,
                    "name":"Orange, Sweet Orange",
                    "latinName": "Citrus sinensis",
                    "color": "lch(76% 48 68)",
                    "colorFallback": "hsl(33 100% 61%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2024,
                    "name":"Palestinian Sweet Lime",
                    "latinName": "Citrus Limettioides",
                    "color": "lch(91% 55 93)",
                    "colorFallback": "hsl(53 98% 58%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2025,
                    "name":"Petitgrain, Orange Leaves",
                    "latinName": "Citrus aurantium ssp. amara",
                    "color": "lch(53% 42 118)",
                    "colorFallback": "hsl(79 100% 28%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2026,
                    "name":"Pomelo",
                    "latinName": "Citrus Maxima",
                    "color": "lch(83% 24 85)",
                    "colorFallback": "hsl(43 64% 73%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2027,
                    "name":"May Chang, Litsea Cubeba",
                    "latinName": "Litsea Cubeba",
                    "color": "lch(83% 32 95)",
                    "colorFallback": "hsl(52 62% 66%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2028,
                    "name":"Lemon Balm, Melissa",
                    "latinName": "Melissa officinalis",
                    "color": "lch(74% 42 125)",
                    "colorFallback": "hsl(92 51% 54%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2029,
                    "name":"Shiikuwasha",
                    "latinName": "Citrus × depressa",
                    "color": "lch(56% 34 118)",
                    "colorFallback": "hsl(82 49% 38%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2030,
                    "name":"Tangerine",
                    "latinName": "Citrus reticulata",
                    "color": "lch(71% 54 68)",
                    "colorFallback": "hsl(37 100% 48%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 2031,
                    "name":"Yuzu",
                    "latinName": "Citrus junos",
                    "color": "lch(82% 55 87)",
                    "colorFallback": "hsl(50 100% 47%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
            ]
        },
    //     {
    //         "scentFamilyId": 3,
    //         "name":"fruits", 
    //         "note": "top",
    //         "scents":[
    //             {
    //                 "scentId": 3001,
    //                 "name":"Acai Berry",
    //                 "latinName": "Euterpe Oleracea",
    //                 "color": "hwb(252 20% 78%)",
    //                 "colorFallback": "",
    //                 "isBasic": false,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 3002,
    //                 "name":"Acerola, Barbados Cherry",
    //                 "latinName": "Malpighia emarginata",
    //                 "color": "hwb(8 18% 0%)",
    //                 "colorFallback": "",
    //                 "isBasic": false,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 3003,
    //                 "name":"Apple",
    //                 "latinName": "Malus domestica",
    //                 "color": "hwb(0 40% 1%)",
    //                 "colorFallback": "",
    //                 "isBasic": true,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 3004,
    //                 "name":"Apricot",
    //                 "latinName": "Prunus armeniaca",
    //                 "color": "hwb(35 0% 0%)",
    //                 "colorFallback": "",
    //                 "isBasic": true,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //         ]
    //     },
    //     {
    //         "scentFamilyId": 1,
    //         "name":"green & herbal", 
    //         "note": "middle",
    //         "scents":[
    //             {
    //                 "scentId": 1001,
    //                 "name":"Agave",
    //                 "latinName": "Agave",
    //                 "color": "#739EA8",
    //                 "colorFallback": "",
    //                 "isBasic": false,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1002,
    //                 "name":"Algae",
    //                 "latinName": "Algae",
    //                 "color": "#95B90C",
    //                 "colorFallback": "",
    //                 "isBasic": false,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1003,
    //                 "name":"Aloe Vera",
    //                 "latinName": "Aloe vera",
    //                 "color": "#7A9143",
    //                 "colorFallback": "",
    //                 "isBasic": true,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1004,
    //                 "name":"Ammophila, Beach Grass",
    //                 "latinName": "Ammophila arenaria",
    //                 "color": "#758651",
    //                 "colorFallback": "",
    //                 "isBasic": false,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1005,
    //                 "name":"Angelica",
    //                 "latinName": "Angelica archangelica",
    //                 "color": "#B2C863",
    //                 "colorFallback": "",
    //                 "isBasic": false,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1006,
    //                 "name":"Apple Mint, Pineapple Mint",
    //                 "latinName": "Mentha suaveolens",
    //                 "color": "#9CD965",
    //                 "colorFallback": "",
    //                 "isBasic": true,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1007,
    //                 "name":"Arnica, Wolf's Bane",
    //                 "latinName": "Arnica montana",
    //                 "color": "#F8CE26",
    //                 "colorFallback": "",
    //                 "isBasic": false,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1008,
    //                 "name":"Artemisia, Wormwood",
    //                 "latinName": "Artemisia absinthium",
    //                 "color": "#8BBEAD",
    //                 "colorFallback": "",
    //                 "isBasic": false,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1009,
    //                 "name":"Asparagus",
    //                 "latinName": "Asparagus Officinalis",
    //                 "color": "#7AB344",
    //                 "colorFallback": "",
    //                 "isBasic": false,
    //                 "image": null,
    //                 "description": "",
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1010,
    //                 "name":"Tea Plant",
    //                 "latinName": "Camellia Sinensis",
    //                 "color": "#489A23",
    //                 "colorFallback": "",
    //                 "isBasic": true,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1011,
    //                 "name":"Avocado",
    //                 "latinName": "Persea americana",
    //                 "color": "#548F2A",
    //                 "colorFallback": "",
    //                 "isBasic": false,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1012,
    //                 "name":"Banana leave",
    //                 "latinName": "Musa acuminate",
    //                 "color": "#7AAB5E",
    //                 "colorFallback": "",
    //                 "isBasic": false,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1013,
    //                 "name":"Barley",
    //                 "latinName": "Hordeum vulgare",
    //                 "color": "#DADF87",
    //                 "colorFallback": "",
    //                 "isBasic": false,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1014,
    //                 "name":"Basil",
    //                 "latinName": "Ocimum basilicum",
    //                 "color": "#62A300",
    //                 "colorFallback": "",
    //                 "isBasic": true,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1015,
    //                 "name":"West Indian Bay Tree, Bay Rum Tree",
    //                 "latinName": "Pimenta racemosa",
    //                 "color": "#8DBD33",
    //                 "colorFallback": "",
    //                 "isBasic": false,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //             {
    //                 "scentId": 1016,
    //                 "name":"Betel Leaf",
    //                 "latinName": "Piper Betle",
    //                 "color": "#60A609",
    //                 "colorFallback": "",
    //                 "isBasic": false,
    //                 "image": null,
    //                 "description": null,
    //                 "referenceLink": null
    //             },
    //         ]
    //     }, 
        {
            "scentFamilyId": 4,
            "name":"flowers", 
            "note": "middle",
            "scents":[
                {
                    "scentId": 4001,
                    "name":"Acacia",
                    "latinName": "Acacia Farnesiana",
                    "color": "lch(82% 1 8)",
                    "colorFallback": "hsl(40 3% 80%)",
                    "isBasic": true,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 4002,
                    "name":"Aglaia",
                    "latinName": "Aglaia odorata",
                    "color": "lch(93% 36 100)",
                    "colorFallback": "hsl(58 83% 73%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 4003,
                    "name":"Almond Blossom",
                    "latinName": "Prunus amygdalus",
                    "color": "lch(90% 7 74)",
                    "colorFallback": "hsl(32 47% 87%)",
                    "colorSecond": "lch(65% 30 4)",
                    "colorSecondFallback": "hsl(343 71% 70%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 4004,
                    "name":"Althaea",
                    "latinName": "Althaea",
                    "color": "lch(94% 2 303)",
                    "colorFallback": "hsl(266 23% 94%)",
                    "colorSecond": "lch(19% 19 18)",
                    "colorSecondFallback": "hsl(351 52% 21%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 4005,
                    "name":"Amarillys, Lily of the Palace",
                    "latinName": "Hippeastrum aulicum",
                    "color": "lch(56% 59 35)",
                    "colorFallback": "hsl(0 94% 59%)",
                    "colorSecond": "lch(69% 43 123)",
                    "colorSecondFallback": "hsl(89 50% 48%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 4006,
                    "name":"Poppy anemone",
                    "latinName": "Anemone coronaria",
                    "color": "lch(54% 43 294)",
                    "colorFallback": "hsl(244 74% 69%)",
                    "colorSecond": "lch(4% 14 282)",
                    "colorSecondFallback": "hsl(227 87% 9%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 4007,
                    "name":"Angel's trumpets",
                    "latinName": "Brugmansia",
                    "color": "lch(84% 41 7)",
                    "colorFallback": "hsl(39 100% 68%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 4008,
                    "name":"Apple Blossom",
                    "latinName": "Malus domestica",
                    "color": "lch(98% 0 20)",
                    "colorFallback": "hsl(20 27% 98%)",
                    "colorSecond": "lch(94% 20 97)",
                    "colorSecondFallback": "hsl(53 83% 84%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 4009,
                    "name":"Apricot Blossom",
                    "latinName": "Prunus mume",
                    "color": "lch(94% 1 275)",
                    "colorFallback": "hsl(228 17% 94%)",
                    "colorSecond": "lch(79% 43 79)",
                    "colorSecondFallback": "hsl(40 86% 61%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
                {
                    "scentId": 4010,
                    "name":"Arum Lily, Calla Lily",
                    "latinName": "Zantedeschia aethiopica",
                    "color": "lch(98% 0 139)",
                    "colorFallback": "hsl(0 0% 98%)",
                    "colorSecond": "lch(85% 37 81)",
                    "colorSecondFallback": "hsl(41 94% 70%)",
                    "isBasic": false,
                    "image": null,
                    "description": null,
                    "referenceLink": null
                },
            ]
        }
    ]